version: "3.7"

services:
  webapp-server:
    env_file: .env
    environment:
      - PORT=9001
      - HOST=0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:9001